omok/pom.xml

Feat : Init project

---

omok/src/main/java/VO/GameListVO.java
omok/src/main/java/VO/ProfileVO.java

- userId를 GameListVO, ProfileVO에 FK 매핑하는 코드 필요

Feat : GameListVO, ProfileVO 구현

---

omok/pom.xml
omok/src/main/java/CustomGameServlet.java
omok/src/main/java/VO/GameListVO.java
omok/src/main/java/VO/ProfileVO.java

- 모든 VO에 외래키 필드 추가
- lombok 의존성 추가
- 랜덤 코드 생성 기능 추가 : [localhost](http://localhost:9090/custom-game) 접속 시 서버에 랜덤 코드가 출력되도록 구현함. 추후 프론트에 출력되도록 연결 할 예정

[Omok 18] 랜덤 입장 코드 생성 기능 구현

---

omok/src/main/java/VO/GameListVO.java
omok/src/main/java/VO/ProfileVO.java
omok/src/main/java/VO/UserVO.java

- long을 integer로 변경
- long type을 integer로 MySQL 타입에 맞게 변경

Fix : GameListVO, ProfileVO, UserVO type 수정

---

omok/pom.xml
omok/src/main/webapp/WEB-INF/view/MainPage.jsp

- MainPage.jsp에서 <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>로 수정
- pom.xml에 의존성 추가
- MainPage.jsp에서 <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>로 수정
- pom.xml에 의존성 추가(https://mvnrepository.com/artifact/javax.servlet/jstl/1.2)

Fix : jstl 오류 해결

---

omok/src/main/java/DAO/LandingDAO.java
omok/src/main/java/DAO/RegisterDAO.java
omok/src/main/java/LandingPageServlet.java
omok/src/main/java/RegisterServlet.java
omok/src/main/webapp/WEB-INF/view/LandingPage.jsp
omok/src/main/webapp/WEB-INF/view/RegisterPage.jsp
omok/src/main/webapp/WEB-INF/view/include/alert.jsp
omok/src/main/webapp/css/index.css
omok/src/main/webapp/css/signup.css
omok/src/main/webapp/js/index.js
omok/src/main/webapp/js/signup.js

일단 UserVO 에 long 을 int 로 바꿔서 작업했습니다. 그리고 UserVO는 commit 치지는 않았어요 충돌을 우려해서 안했습니다.
!!! -> 세션을 구현했습니다. 로그인하면 세션이 생성됩니다. 로그인 된 상태라면 session.getAttribute("user") 를 사용할수 있습니다.
landingDAO.java
LandingPageServlet.java 
LandingPage.jsp 
index.css 
index.js
RegisterDAO.java
RegisterServlet.java
RegisterPage.jsp
signup.css
signup.js
- alert.jsp 추가
- js 폴더 추가
- include 폴더 추가
수정 말씀하시면 수정할게요

[Omok06] 로그인 기능 구현 [Omok07] 회원가입 기능 구현

---

omok/pom.xml
omok/src/main/java/CustomGameServlet.java
omok/src/main/java/DAO/CustomGameDAO.java
omok/src/main/java/MainPageServlet.java
omok/src/main/java/VO/GameListVO.java
omok/src/main/java/VO/ProfileVO.java
omok/src/main/webapp/WEB-INF/view/CustomGamePage.jsp
omok/src/main/webapp/css/game.css

- 자동으로 방 번호 증가
- is_custom을 자동으로 true로 설정하도록 로직 작성
- 방 생성과 동시에 DB에 입장 코드 저장

[Omok11] 방 생성 기능 구현

---

omok/src/main/java/CustomGameServlet.java
omok/src/main/java/DAO/CustomGameDAO.java

- 방 index는 DB에서 자동 증가
- 방 생성 시 is_custom 값을 true로 설정하는 기능 구현 완료
- 생성된 gameCode 값을 DB에 저장하는 로직 구현 완료

[Omok 11] 방 생성 기능 구현

---

omok/src/main/java/CustomGameServlet.java
omok/src/main/java/DAO/CustomGameDAO.java
omok/src/main/webapp/WEB-INF/view/CustomGamePage.jsp

- 공개방 전환 버튼을 누르면 페이지 이동
- roomCode를 서버에서 받아와 DB에서 검색 후, 일치하는 방의 is_custom 값을 flase로 변경
- 페이지 및 DB 테스트 완료

[Omok21] 방 공개/비공개 설정 기능

---

omok/src/main/java/DAO/RandomGameDAO.java
omok/src/main/java/RandomGameServlet.java
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp
omok/src/main/webapp/css/game.css

랜덤 게임 DAO 생성 및 user 조회 기능 추가 
랜덤 게임 JSP 오목알 두기 기능 구현 (프론트에서 html, css, js로 구현)

랜덤 게임 DAO 생성 및 JSP상 오목알 두기 기능 구현

---

omok/src/main/java/CustomGameServlet.java
omok/src/main/java/DAO/CustomGameDAO.java

Comment : 주석 오타 수정

---

omok/pom.xml
omok/src/main/java/CreateRoomServlet.java
omok/src/main/java/WebSocket.java
omok/src/main/webapp/WEB-INF/view/MainPage.jsp
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp
omok/src/main/webapp/css/clock.css
omok/src/main/webapp/css/modal.css

- 웹 소켓 연결 기초 구현
- handleOpen메서드 -> 소켓 연결시 기능 구현

feat: Add WebSocket connect

---

omok/src/main/java/DAO/RandomGameDAO.java
omok/src/main/java/RandomGameServlet.java
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp

RandomGameDAO상 공개방 생성, 비공개방으로 전환 기능 추가
오목알 두기 영역 밖 벗어나지 않게하는 로직 추가

공개방 생성 및 오목알 두기 좌표 영역 수정

---

omok/src/main/java/EnterRoomServlet.java

EnterRoomServlet에서 참여할 수 있는 방이 없을 때, 메인페이지로 돌아가서 alert 메시지 띄울 수 있도록 함.

Feat: Add alert in EnterRoomServlet

---

omok/src/main/java/LogoutServlet.java
omok/src/main/webapp/WEB-INF/view/MainPage.jsp

[Omok13] 로그아웃 기능 구현

---

omok/pom.xml
omok/src/main/java/DAO/RandomGameDAO.java
omok/src/main/java/EnterRoomServlet.java
omok/src/main/java/LandingPageServlet.java
omok/src/main/java/WebSocket.java
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp

- WebSocket 기반 실시간 채팅 기능 구현
- RandomGamePage만 수정 완료 (CustomGamePage.jsp 수정 필요)

[Omok16] 실시간 채팅 기능 구현

---

omok/src/main/java/DAO/UserDAO.java
omok/src/main/java/RegisterServlet.java
omok/src/main/webapp/css/signup.css

- RegisterDAO -> UserDAO로 파일명 수정
- 회원가입 시 아이디 중복확인 안되는 기능 수정
- 중복확인 버튼 CSS 수정

Fix: Modify Duplicate Check

---

omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp

Fix: Modify RandomGamePage

---

omok/src/main/webapp/WEB-INF/view/CustomGamePage.jsp
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp

공개방, 비공개방 전환 버튼 클릭 시 기능 실행할 수 있도록 function 추가

Add change room function on random/custom jsp page

---

omok/src/main/webapp/WEB-INF/view/CustomGamePage.jsp
omok/src/main/webapp/WEB-INF/view/MainPage.jsp
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp

Fix: Fix change room type function

---

omok/src/main/webapp/WEB-INF/view/CustomGamePage.jsp
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp

feat: Set custom game page

---

omok/src/main/java/UserServlet.java
omok/src/main/webapp/WEB-INF/view/CustomGamePage.jsp
omok/src/main/webapp/WEB-INF/view/MainPage.jsp
omok/src/main/webapp/WEB-INF/view/RandomGamePage.jsp
omok/src/main/webapp/WEB-INF/view/RegisterPage.jsp
omok/src/main/webapp/WEB-INF/view/include/alert.jsp
omok/src/main/webapp/css/common.css
omok/src/main/webapp/js/signup.js

Deisgn: Modify the Alert Popup Design to SweetAlert2

 Deisgn: Modify the Alert Popup Design

---

omok/src/main/java/CreateRoomServlet.java
omok/src/main/java/DAO/WinLoseDAO.java
omok/src/main/java/WinLoseServlet.java

- WinloseDAO, WinLoseServlet 파일 추가

Feat: Add Win-Lose Feature
